// automatically generated by the FlatBuffers compiler, do not modify

package com.example.scrumpoker.data;

public final class EventType {
  private EventType() { }
  public static final byte Added = 0;
  public static final byte Updated = 1;
  public static final byte Removed = 2;

  public static final String[] names = { "Added", "Updated", "Removed", };

  public static String name(int e) { return names[e]; }
}

