// automatically generated by the FlatBuffers compiler, do not modify

package com.example.scrumpoker.data;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PlayerId extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static PlayerId getRootAsPlayerId(ByteBuffer _bb) { return getRootAsPlayerId(_bb, new PlayerId()); }
  public static PlayerId getRootAsPlayerId(ByteBuffer _bb, PlayerId obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PlayerId __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createPlayerId(FlatBufferBuilder builder,
      int idOffset) {
    builder.startTable(1);
    PlayerId.addId(builder, idOffset);
    return PlayerId.endPlayerId(builder);
  }

  public static void startPlayerId(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static int endPlayerId(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PlayerId get(int j) { return get(new PlayerId(), j); }
    public PlayerId get(PlayerId obj, int j) {  return obj.__assign(Table.__indirect(__element(j), bb), bb); }
  }
}

