// automatically generated by the FlatBuffers compiler, do not modify

package com.example.scrumpoker.data;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class RoomEvent extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static RoomEvent getRootAsRoomEvent(ByteBuffer _bb) { return getRootAsRoomEvent(_bb, new RoomEvent()); }
  public static RoomEvent getRootAsRoomEvent(ByteBuffer _bb, RoomEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RoomEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String id() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public com.example.scrumpoker.data.Player owner() { return owner(new com.example.scrumpoker.data.Player()); }
  public com.example.scrumpoker.data.Player owner(com.example.scrumpoker.data.Player obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public com.example.scrumpoker.data.Player players(int j) { return players(new com.example.scrumpoker.data.Player(), j); }
  public com.example.scrumpoker.data.Player players(com.example.scrumpoker.data.Player obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int playersLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public com.example.scrumpoker.data.Player.Vector playersVector() { return playersVector(new com.example.scrumpoker.data.Player.Vector()); }
  public com.example.scrumpoker.data.Player.Vector playersVector(com.example.scrumpoker.data.Player.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createRoomEvent(FlatBufferBuilder builder,
      byte type,
      int idOffset,
      int ownerOffset,
      int playersOffset) {
    builder.startTable(4);
    RoomEvent.addPlayers(builder, playersOffset);
    RoomEvent.addOwner(builder, ownerOffset);
    RoomEvent.addId(builder, idOffset);
    RoomEvent.addType(builder, type);
    return RoomEvent.endRoomEvent(builder);
  }

  public static void startRoomEvent(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(1, idOffset, 0); }
  public static void addOwner(FlatBufferBuilder builder, int ownerOffset) { builder.addOffset(2, ownerOffset, 0); }
  public static void addPlayers(FlatBufferBuilder builder, int playersOffset) { builder.addOffset(3, playersOffset, 0); }
  public static int createPlayersVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPlayersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endRoomEvent(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishRoomEventBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedRoomEventBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RoomEvent get(int j) { return get(new RoomEvent(), j); }
    public RoomEvent get(RoomEvent obj, int j) {  return obj.__assign(Table.__indirect(__element(j), bb), bb); }
  }
}

